<a href="https://colab.research.google.com/github/ywei6056/Intro.-Experimental-Physics-I-NYU/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#[PyMan 0.9.31 Introduction to Python for Science](https://www.taylorfrancis.com/books/mono/10.1201/9780429506413/introduction-python-science-engineering-david-pine)

###The following exercises correspond to chapter [4: Input and Output](https://www.taylorfrancis.com/chapters/mono/10.1201/9780429506413-4/input-output-david-pine)

[old chapter link](https://physics.nyu.edu/pine/pymanual/html/chap4/chap4_io.html)

In [ ]:
import numpy as np

Look left <-----

There's a folder icon on the bar. 

Click it. 

You should see a folder called "sample_data." You don't need this sample data! It's a gift from google that you don't want. I wish there was some kind of [metaphor](https://www.dailymotion.com/video/x2hwqlw) for this situation.

The code block below will download the data file and display its contents. 

In [ ]:
!wget -nc https://raw.githubusercontent.com/NYUExperimentalPhysics1-2021/Assignment4/main/assignment4data.txt
!more assignment4data.txt

File ‘assignment4data.txt’ already there; not retrieving.

Date: 2013-09-16
Data taken by Liam and Selena
frequency (Hz) amplitude (mm)  amp error (mm)
  0.7500        13.52         0.32
  1.7885        12.11         0.92
  2.8269        14.27         0.73
  3.8654        16.60         2.06
  4.9038        22.91         1.75
  5.9423        35.28         0.91
  6.9808        60.99         0.99
  8.0192        33.38         0.36
  9.0577        17.78         2.32
 10.0962        10.99         0.21
 11.1346         7.47         0.48
 12.1731         6.72         0.51
 13.2115         4.40         0.58
 14.2500         4.07         0.63


You should check to see if your file is there. Click the folder with the circle arrow above the file lists (below the world Files); if you hover, it will say "Refresh." Once it refreshes, you should see the file assignment4data.txt in the directory below the sample_data folder.


##4.5.1

Write a Python program that calculates how much money you can spend each day for lunch for the rest of the month based on today's date and how much money you currently have in your lunch account. The program should ask you: (1) how much money you have in your account, (2) what today's date is, and (3) how many days there are in this month. The program should return your daily allowance. The results of running your program should look like this:

```
How much money (in dollars) in your lunch account? 118.39

What day of the month is today? 17

How many days in this month? 30

You can spend $8.46 each day for the rest of the month.
```

_Extra:_ Create a dictionary (see _[Dictionaries](https://physics.nyu.edu/pine/pymanual/html/chap3/chap3_arrays.html#chap3dictionaries)_) that stores the number of days in each month (forget about leap years) and have your program ask what month it is rather than the number of days in the month.

In [ ]:
savings = input('How much money (in dollars) is in your lunch account?')
date = input('What day of the month is today?')
days = input('How many days are there in this month?')

savings = float(savings)
date = eval(date)
days = eval(days)

daysleft = days - date + 1
allowance = savings/daysleft
print("You can spend $ {:.2f} on your lunch every day for the rest of this month.".format(allowance))

How much money (in dollars) is in your lunch account?118.39
What day of the month is today?17
How many days are there in this month?30
You can spend $ 8.46 on your lunch every day for the rest of this month.


##4.5.2

From the IPython terminal, create the following three NumPy arrays:

```
a = array([1, 3, 5, 7])
b = array([8, 7, 5, 4])
c = array([0, 9,-6,-8])
```

Now use the `zip` function to create the object `d` defined as

```
d = zip(a, b, c)
```

Print `d` out at the terminal prompt. What kind of object is `d`? Hint: It is not a NumPy array. Convert `d` into a NumPy array and call that array `e`. Type `e` at the terminal prompt so that `e` is printed out on the IPython terminal. One of the elements of `e` is `-8`. Show how to address and print out just that element of `e`. Show how to address that same element of `d`. What has become of the three original arrays `a`,`b`, and `c`, that is, how do they appear in `e`?

In [ ]:
a = np.array([1, 3, 5, 7])
b = np.array([8, 7, 5, 4])
c = np.array([0, 9,-6,-8])
print("What is d?")
d = zip(a, b, c)
print(d)
print(type(d))

#???
print("I think d is a zip object. We can use a command such as print(tuple(d)) to display d in a readable format")

print("What kind of object is e?")
e=np.array(d)
print(type(e))
print(e)

print("I couldn't make it to the TA Office Hours this week so I am not sure why e is still printing out as an unreadable version even though it is a numpy array, but this is what I think I should do:")
print("Making d into a list format:")
d = list(zip(a, b, c))
print(type(d))
print(d)

print("Now converting d to e, a numpy array:")
e=np.array(d)
print(type(e))
print(e)

print("What kinds of objects are contained in e?")
print(type(e[3]))
print("Calling the 2nd index of the last object in e:")
print(e[3][2])

print("What kinds of objects are contained in d?")
print(type(d[3]))
#note to self: tuples are ordered, callable, but cannote be mutated (unlike lists)
print("Calling the 2nd index of the last object in d:")
print(d[3][2])

print("Answer: d is a collection/list of tuples, while e is an array of four smaller arrays. Elements in both are callable, and elements within tuples and arrays are also callable by index.")
print("a, b, c appear as numpy arrays in e")

What is d?
<class 'zip'>
I think d is a zip object. We can use a command such as print(tuple(d)) to display d in a readable format
What kind of object is e?
<class 'numpy.ndarray'>
I couldn't make it to the TA Office Hours this week so I am not sure why e is still printing out as an unreadable version even though it is a numpy array, but this is what I think I should do:
Making d into a list format:
<class 'list'>
[(1, 8, 0), (3, 7, 9), (5, 5, -6), (7, 4, -8)]
Now converting d to e, a numpy array:
<class 'numpy.ndarray'>
[[ 1  8  0]
 [ 3  7  9]
 [ 5  5 -6]
 [ 7  4 -8]]
What kinds of objects are contained in e?
<class 'numpy.ndarray'>
Calling the 2nd index of the last object in e:
-8
What kinds of objects are contained in d?
<class 'tuple'>
Calling the 2nd index of the last object in d:
-8
Answer: d is a collection/list of tuples, while e is an array of four smaller arrays. Elements in both are callable, and elements within tuples and arrays are also callable by index.
a, b, c appear as

##4.5.3

Write a Python script to read "assignment4data.txt" into three NumPy arrays with the variable names `f`,`a`,`da` for the frequency, amplitude, and amplitude error.

```
Date: 2013-09-16
Data taken by Liam and Selena
frequency (Hz) amplitude (mm)  amp error (mm)
  0.7500        13.52         0.32
  1.7885        12.11         0.92
  2.8269        14.27         0.73
  3.8654        16.60         2.06
  4.9038        22.91         1.75
  5.9423        35.28         0.91
  6.9808        60.99         0.99
  8.0192        33.38         0.36
  9.0577        17.78         2.32
 10.0962        10.99         0.21
 11.1346         7.47         0.48
 12.1731         6.72         0.51
 13.2115         4.40         0.58
 14.2500         4.07         0.63
 ```

Show that you have correctly read in the data by having your script print out to your computer screen the three arrays. Format the printing so that it produces output like this:

```
f =
[  0.75     1.7885   2.8269   3.8654   4.9038   5.9423
   6.9808   8.0192   9.0577  10.0962  11.1346  12.1731
   13.2115  14.25  ]
a =
[ 13.52  12.11  14.27  16.6   22.91  35.28  60.99  33.38
  17.78  10.99   7.47   6.72   4.4    4.07]
da =
[ 0.32  0.92  0.73  2.06  1.75  0.91  0.99  0.36  2.32
  0.21  0.48  0.51  0.58  0.63]
```

Note that the array `f` is displayed with four digits to the right of the decimal point while the arrays `a` and `da` are displayed with only two. The columns of the displayed arrays need not line up as they do above.

In [ ]:
f,a,da = np.loadtxt("assignment4data.txt", skiprows=3, unpack=True)
print("f = {}".format(f))
print("a = {}".format(a))
print("da = {}".format(da))


f=[ 0.75    1.7885  2.8269  3.8654  4.9038  5.9423  6.9808  8.0192  9.0577
 10.0962 11.1346 12.1731 13.2115 14.25  ]
a=[13.52 12.11 14.27 16.6  22.91 35.28 60.99 33.38 17.78 10.99  7.47  6.72
  4.4   4.07]
da=[0.32 0.92 0.73 2.06 1.75 0.91 0.99 0.36 2.32 0.21 0.48 0.51 0.58 0.63]


##4.5.4

Now write the data you just read (`f`, `a`, `da`)  to a data file, including the header, with the data displayed in three columns, just as its displayed in the problem above. It's ok if the header lines begin with the `#` comment character. Your data file should be called `textfileanswer.txt`. 

In [ ]:
headers = 'Data taken by Liam and Selena'
headers +='\nDate: 2013-09-16'
headers +='\n\n Frequency(Hz), Amplitude(mm), Amplitude Error(mm)'
np.savetxt('textfileanswer.txt', list(zip(f, a, da)), header=headers, fmt="%15.4f")

#is there a way to make the numbers line up with the headers?
#(also, how can the headers become strings that get read in with the numbers?)

##4.5.5

Now write the same data to a csv data file, **without the header**, to a data file called `csvfileanswer.csv` with the data displayed in three columns. Use a single format specifier and set it to `"%0.16e"`. If you have access to a spreadsheet program (like MS Excel), try opening the file you have created with your Python script and verify that the arrays are displayed in three columns. Note that your csv file should have the extension `.csv`.

In [ ]:
np.savetxt('csvfileanswer.csv', list(zip(f, a, da)), delimiter=",", fmt="%0.16e")

#YOU'RE NOT DONE!

First, you should save a copy of this notebook to your github repository, using File>Save a copy in github, as usual. But this only commits your notebook. You'll also need to save the data files you created too!

As soon as you close this browser, your beautiful files `textanswer.txt` and `csvanswer.csv` will dissappear into the ether. You need to turn them in so you can get a grade! 

1. Click on the dots next to each file's name (or right click on the file name) and select download. 

2. Open your repository on github ( it will be located at
https://github.com/NYUExperimentalPhysics1-2021/assignment4-yourgithubusername  - you can also get to the repository from the github page that opens when you save your notebook in github) and click on the "add file" button and select upload. **OR**  you can go straight to the upload page at
https://github.com/NYUExperimentalPhysics1-2021/assignment4-yourgithubusername/upload/main
You'll have to replace "yourgithubusername" with your github username

3. Drag the files you downloaded in Step 1 onto the upload box. 

4. Click commit changes (you can edit the commit message first if you want)


